# Generated by Django 3.2 on 2024-01-20 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HoPsapp', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hops',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
